/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type DjId = bigint;
export interface DJ {
    id: DjId;
    bio: string;
    name: string;
    createdAt: Time;
    photoUrl: string;
}
export type ShowId = bigint;
export type Time = bigint;
export interface Show {
    id: ShowId;
    title: string;
    djId?: DjId;
    createdAt: Time;
    description: string;
    scheduleTime: string;
    scheduleDay: string;
}
export interface backendInterface {
    assignDjToShow(showId: ShowId, djId: DjId): Promise<void>;
    createDj(name: string, bio: string, photoUrl: string): Promise<DjId>;
    createShow(title: string, description: string, scheduleDay: string, scheduleTime: string): Promise<ShowId>;
    getAllDjs(): Promise<Array<DJ>>;
    getAllShows(): Promise<Array<Show>>;
    getCurrentShow(): Promise<Show | null>;
    getDj(id: DjId): Promise<DJ>;
    getShow(id: ShowId): Promise<Show>;
}
import type { DjId as _DjId, Show as _Show, ShowId as _ShowId, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignDjToShow(arg0: ShowId, arg1: DjId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignDjToShow(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignDjToShow(arg0, arg1);
            return result;
        }
    }
    async createDj(arg0: string, arg1: string, arg2: string): Promise<DjId> {
        if (this.processError) {
            try {
                const result = await this.actor.createDj(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDj(arg0, arg1, arg2);
            return result;
        }
    }
    async createShow(arg0: string, arg1: string, arg2: string, arg3: string): Promise<ShowId> {
        if (this.processError) {
            try {
                const result = await this.actor.createShow(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShow(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAllDjs(): Promise<Array<DJ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDjs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDjs();
            return result;
        }
    }
    async getAllShows(): Promise<Array<Show>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShows();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShows();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentShow(): Promise<Show | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentShow();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentShow();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDj(arg0: DjId): Promise<DJ> {
        if (this.processError) {
            try {
                const result = await this.actor.getDj(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDj(arg0);
            return result;
        }
    }
    async getShow(arg0: ShowId): Promise<Show> {
        if (this.processError) {
            try {
                const result = await this.actor.getShow(arg0);
                return from_candid_Show_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShow(arg0);
            return from_candid_Show_n2(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Show_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Show): Show {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DjId]): DjId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Show]): Show | null {
    return value.length === 0 ? null : from_candid_Show_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ShowId;
    title: string;
    djId: [] | [_DjId];
    createdAt: _Time;
    description: string;
    scheduleTime: string;
    scheduleDay: string;
}): {
    id: ShowId;
    title: string;
    djId?: DjId;
    createdAt: Time;
    description: string;
    scheduleTime: string;
    scheduleDay: string;
} {
    return {
        id: value.id,
        title: value.title,
        djId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.djId)),
        createdAt: value.createdAt,
        description: value.description,
        scheduleTime: value.scheduleTime,
        scheduleDay: value.scheduleDay
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Show>): Array<Show> {
    return value.map((x)=>from_candid_Show_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
