/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DJ {
  'id' : DjId,
  'bio' : string,
  'name' : string,
  'createdAt' : Time,
  'photoUrl' : string,
}
export type DjId = bigint;
export interface Show {
  'id' : ShowId,
  'title' : string,
  'djId' : [] | [DjId],
  'createdAt' : Time,
  'description' : string,
  'scheduleTime' : string,
  'scheduleDay' : string,
}
export type ShowId = bigint;
export type Time = bigint;
export interface _SERVICE {
  'assignDjToShow' : ActorMethod<[ShowId, DjId], undefined>,
  'createDj' : ActorMethod<[string, string, string], DjId>,
  'createShow' : ActorMethod<[string, string, string, string], ShowId>,
  'getAllDjs' : ActorMethod<[], Array<DJ>>,
  'getAllShows' : ActorMethod<[], Array<Show>>,
  /**
   * / Returns the currently scheduled show based on CST (Central Standard Time, UTC-6).
   * / The method applies the UTC-6 offset to the IC system time, determines the current
   * / CST day and time, and matches it against each show's schedule.
   */
  'getCurrentShow' : ActorMethod<[], [] | [Show]>,
  'getDj' : ActorMethod<[DjId], DJ>,
  'getShow' : ActorMethod<[ShowId], Show>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];