/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ShowId = IDL.Nat;
export const DjId = IDL.Nat;
export const Time = IDL.Int;
export const DJ = IDL.Record({
  'id' : DjId,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'photoUrl' : IDL.Text,
});
export const Show = IDL.Record({
  'id' : ShowId,
  'title' : IDL.Text,
  'djId' : IDL.Opt(DjId),
  'createdAt' : Time,
  'description' : IDL.Text,
  'scheduleTime' : IDL.Text,
  'scheduleDay' : IDL.Text,
});

export const idlService = IDL.Service({
  'assignDjToShow' : IDL.Func([ShowId, DjId], [], []),
  'createDj' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [DjId], []),
  'createShow' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ShowId],
      [],
    ),
  'getAllDjs' : IDL.Func([], [IDL.Vec(DJ)], ['query']),
  'getAllShows' : IDL.Func([], [IDL.Vec(Show)], ['query']),
  'getDj' : IDL.Func([DjId], [DJ], ['query']),
  'getShow' : IDL.Func([ShowId], [Show], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ShowId = IDL.Nat;
  const DjId = IDL.Nat;
  const Time = IDL.Int;
  const DJ = IDL.Record({
    'id' : DjId,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'photoUrl' : IDL.Text,
  });
  const Show = IDL.Record({
    'id' : ShowId,
    'title' : IDL.Text,
    'djId' : IDL.Opt(DjId),
    'createdAt' : Time,
    'description' : IDL.Text,
    'scheduleTime' : IDL.Text,
    'scheduleDay' : IDL.Text,
  });
  
  return IDL.Service({
    'assignDjToShow' : IDL.Func([ShowId, DjId], [], []),
    'createDj' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [DjId], []),
    'createShow' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ShowId],
        [],
      ),
    'getAllDjs' : IDL.Func([], [IDL.Vec(DJ)], ['query']),
    'getAllShows' : IDL.Func([], [IDL.Vec(Show)], ['query']),
    'getDj' : IDL.Func([DjId], [DJ], ['query']),
    'getShow' : IDL.Func([ShowId], [Show], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };